const fakeEmployees = [
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2023-01-15',
        dateOfBirth: '1990-03-22',
        street: '123 Main St',
        city: 'New York',
        state: 'NY',
        department: 'Engineering',
        zipCode: '10001',
    },
    {
        firstName: 'Jane',
        lastName: 'Smith',
        startDate: '2022-11-20',
        dateOfBirth: '1985-07-12',
        street: '456 Elm St',
        city: 'Los Angeles',
        state: 'CA',
        department: 'Marketing',
        zipCode: '90001',
    },
    {
        firstName: 'Michael',
        lastName: 'Johnson',
        startDate: '2023-02-05',
        dateOfBirth: '1988-01-30',
        street: '789 Maple Ave',
        city: 'Chicago',
        state: 'IL',
        department: 'Sales',
        zipCode: '60601',
    },
    {
        firstName: 'Emily',
        lastName: 'Davis',
        startDate: '2022-08-15',
        dateOfBirth: '1992-09-08',
        street: '321 Oak St',
        city: 'Houston',
        state: 'TX',
        department: 'HR',
        zipCode: '77001',
    },
    {
        firstName: 'David',
        lastName: 'Martinez',
        startDate: '2021-05-23',
        dateOfBirth: '1987-12-17',
        street: '654 Pine Rd',
        city: 'Phoenix',
        state: 'AZ',
        department: 'Finance',
        zipCode: '85001',
    },
    {
        firstName: 'Sophia',
        lastName: 'Lopez',
        startDate: '2023-03-12',
        dateOfBirth: '1994-11-03',
        street: '987 Cedar Ln',
        city: 'Philadelphia',
        state: 'PA',
        department: 'IT',
        zipCode: '19101',
    },
    {
        firstName: 'James',
        lastName: 'Brown',
        startDate: '2022-09-19',
        dateOfBirth: '1991-05-14',
        street: '111 Birch St',
        city: 'San Antonio',
        state: 'TX',
        department: 'Operations',
        zipCode: '78201',
    },
    {
        firstName: 'Olivia',
        lastName: 'Garcia',
        startDate: '2021-12-30',
        dateOfBirth: '1989-06-21',
        street: '222 Willow Ave',
        city: 'San Diego',
        state: 'CA',
        department: 'Customer Service',
        zipCode: '92101',
    },
    {
        firstName: 'Lucas',
        lastName: 'Miller',
        startDate: '2023-04-18',
        dateOfBirth: '1993-02-28',
        street: '333 Spruce St',
        city: 'Dallas',
        state: 'TX',
        department: 'Legal',
        zipCode: '75201',
    },
    {
        firstName: 'Ava',
        lastName: 'Wilson',
        startDate: '2022-07-01',
        dateOfBirth: '1995-10-10',
        street: '444 Aspen Way',
        city: 'San Jose',
        state: 'CA',
        department: 'R&D',
        zipCode: '95101',
    },
];

const states = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
];

const departements = [
    "Sales",
    "Marketing",
    "Engineering",
    "Human Resources",
    "Legal"
];


export { fakeEmployees, states, departements };